const RESOURCE_PATH = 'assets';
const DEST_PATH = 'public';
const DEST_ASSETS_PATH = `${DEST_PATH}/assets`;

const FONTS_SRC = `${RESOURCE_PATH}/fonts`;
const IMAGES_SRC = `${RESOURCE_PATH}/img`;
const SCRIPTS_SRC = `${RESOURCE_PATH}/js`;
const STYLES_SRC = `${RESOURCE_PATH}/scss`;
const SPRITES_SRC = `${IMAGES_SRC}/sprites`;

const FONTS_DEST = `${DEST_ASSETS_PATH}/fonts`;
const IMAGES_DEST = `${DEST_ASSETS_PATH}/img`;
const SCRIPTS_DEST = `${DEST_ASSETS_PATH}/js`;
const STYLES_DEST = `${DEST_ASSETS_PATH}/css`;
const VIEWS_DEST = `${RESOURCE_PATH}/views`;
const SPRITES_DEST = `${VIEWS_DEST}/svg`;

export {
  DEST_PATH,
  FONTS_SRC,
  IMAGES_SRC,
  SCRIPTS_SRC,
  STYLES_SRC,
  SPRITES_SRC,
  FONTS_DEST,
  IMAGES_DEST,
  SCRIPTS_DEST,
  STYLES_DEST,
  VIEWS_DEST,
  SPRITES_DEST
};
